// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THOBOTTO.Data;

#nullable disable

namespace THOBOTTO.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20261008004931_PermissionsAndRenames")]
    partial class PermissionsAndRenames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THOBOTTO.Access.PermissionGrant", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("GuildId", "RoleId", "Permission")
                        .HasName("pk_permission_grants");

                    b.ToTable("permission_grants", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Data.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("GuildId", "CreatedAt")
                        .HasDatabaseName("ix_audit_entries_guild_id_created_at");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Data.EnabledModule", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Module")
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("GuildId", "Module")
                        .HasName("pk_enabled_modules");

                    b.ToTable("enabled_modules", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.GameServers.GameServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_game_servers");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_game_servers_guild_id");

                    b.ToTable("game_servers", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.GameServers.ServerSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal?>("BoardChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("board_channel_id");

                    b.Property<int>("FailuresBeforeOffline")
                        .HasColumnType("integer")
                        .HasColumnName("failures_before_offline");

                    b.Property<int>("MaxPerMember")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_member");

                    b.Property<int>("MaxServers")
                        .HasColumnType("integer")
                        .HasColumnName("max_servers");

                    b.Property<bool>("MembersCanAdd")
                        .HasColumnType("boolean")
                        .HasColumnName("members_can_add");

                    b.Property<int>("PollSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_seconds");

                    b.HasKey("GuildId")
                        .HasName("pk_server_settings");

                    b.ToTable("server_settings", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.Rename", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("NewName")
                        .HasColumnType("text")
                        .HasColumnName("new_name");

                    b.Property<string>("OldName")
                        .HasColumnType("text")
                        .HasColumnName("old_name");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_renames");

                    b.HasIndex("GuildId", "TargetId", "CreatedAt")
                        .HasDatabaseName("ix_renames_guild_id_target_id_created_at");

                    b.ToTable("renames", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.DynamicVoiceChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("owner_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_dynamic_voice_channels");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_dynamic_voice_channels_guild_id");

                    b.ToTable("dynamic_voice_channels", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.VoiceHub", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_voice_hubs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_voice_hubs_guild_id");

                    b.ToTable("voice_hubs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
