// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THOBOTTO.Data;

#nullable disable

namespace THOBOTTO.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20261008124837_EventVoice")]
    partial class EventVoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THOBOTTO.Access.PermissionGrant", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("GuildId", "RoleId", "Permission")
                        .HasName("pk_permission_grants");

                    b.ToTable("permission_grants", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Archive.ArchivedAttachment", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset?>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.Property<string>("StoredKey")
                        .HasColumnType("text")
                        .HasColumnName("stored_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<DateTimeOffset>("UrlFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("url_fetched_at");

                    b.HasKey("Id")
                        .HasName("pk_archived_attachments");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_archived_attachments_message_id");

                    b.ToTable("archived_attachments", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Archive.ArchivedMessage", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.HasKey("Id")
                        .HasName("pk_archived_messages");

                    b.HasIndex("GuildId", "AuthorId")
                        .HasDatabaseName("ix_archived_messages_guild_id_author_id");

                    b.HasIndex("GuildId", "ChannelId", "Id")
                        .HasDatabaseName("ix_archived_messages_guild_id_channel_id_id");

                    b.ToTable("archived_messages", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Archive.BackfillChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal?>("Cursor")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("cursor");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<int>("Fetched")
                        .HasColumnType("integer")
                        .HasColumnName("fetched");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Problem")
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.HasKey("ChannelId")
                        .HasName("pk_backfill_channels");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_backfill_channels_guild_id");

                    b.ToTable("backfill_channels", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Archive.BackfillRun", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("Running")
                        .HasColumnType("boolean")
                        .HasColumnName("running");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("GuildId")
                        .HasName("pk_backfill_runs");

                    b.ToTable("backfill_runs", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Archive.MessageVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<DateTimeOffset>("ReplacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_at");

                    b.HasKey("Id")
                        .HasName("pk_message_versions");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_versions_message_id");

                    b.ToTable("message_versions", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Data.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("GuildId", "CreatedAt")
                        .HasDatabaseName("ix_audit_entries_guild_id_created_at");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Data.EnabledModule", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Module")
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("GuildId", "Module")
                        .HasName("pk_enabled_modules");

                    b.ToTable("enabled_modules", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowProposals")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_proposals");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscordEventId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_event_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<decimal?>("PingRoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ping_role_id");

                    b.Property<DateTimeOffset?>("PollClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("poll_closes_at");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_sent");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<bool>("StartSent")
                        .HasColumnType("boolean")
                        .HasColumnName("start_sent");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal?>("VoiceChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("voice_channel_id");

                    b.Property<string>("VoiceMode")
                        .HasColumnType("text")
                        .HasColumnName("voice_mode");

                    b.Property<bool>("WantsDiscordEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("wants_discord_event");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("SeriesId", "StartsAt")
                        .HasDatabaseName("ix_events_series_id_starts_at");

                    b.HasIndex("GuildId", "State", "StartsAt")
                        .HasDatabaseName("ix_events_guild_id_state_starts_at");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.EventRsvp", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EventId", "UserId")
                        .HasName("pk_event_rsvps");

                    b.ToTable("event_rsvps", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.EventSeries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.PrimitiveCollection<int[]>("Days")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("days");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("OpenDaysAhead")
                        .HasColumnType("integer")
                        .HasColumnName("open_days_ahead");

                    b.Property<decimal?>("PingRoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ping_role_id");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("integer")
                        .HasColumnName("time_of_day");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VoiceMode")
                        .HasColumnType("text")
                        .HasColumnName("voice_mode");

                    b.Property<bool>("WantsDiscordEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("wants_discord_event");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_event_series");

                    b.ToTable("event_series", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.EventTimeOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal>("ProposedById")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("proposed_by_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_event_time_options");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_time_options_event_id");

                    b.ToTable("event_time_options", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.EventTimeVote", b =>
                {
                    b.Property<long>("OptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("OptionId", "UserId")
                        .HasName("pk_event_time_votes");

                    b.ToTable("event_time_votes", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Events.MemberTimeZone", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("UserId")
                        .HasName("pk_member_time_zones");

                    b.ToTable("member_time_zones", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Expressions.Expression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Animated")
                        .HasColumnType("boolean")
                        .HasColumnName("animated");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<decimal?>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("LiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("live_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Paid")
                        .HasColumnType("double precision")
                        .HasColumnName("paid");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<decimal>("ProposerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("proposer_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<long?>("RevivedFromId")
                        .HasColumnType("bigint")
                        .HasColumnName("revived_from_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.Property<decimal?>("VoteChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("vote_channel_id");

                    b.Property<DateTimeOffset>("VoteEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vote_ends_at");

                    b.Property<decimal?>("VoteMessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("vote_message_id");

                    b.HasKey("Id")
                        .HasName("pk_expressions");

                    b.HasIndex("GuildId", "Kind", "State")
                        .HasDatabaseName("ix_expressions_guild_id_kind_state");

                    b.ToTable("expressions", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Expressions.ExpressionVote", b =>
                {
                    b.Property<long>("ExpressionId")
                        .HasColumnType("bigint")
                        .HasColumnName("expression_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<bool>("Up")
                        .HasColumnType("boolean")
                        .HasColumnName("up");

                    b.HasKey("ExpressionId", "UserId")
                        .HasName("pk_expression_votes");

                    b.ToTable("expression_votes", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Fame.FameEntry", b =>
                {
                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("InductedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inducted_at");

                    b.Property<int>("Reactors")
                        .HasColumnType("integer")
                        .HasColumnName("reactors");

                    b.Property<decimal?>("ShowcaseMessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("showcase_message_id");

                    b.HasKey("MessageId")
                        .HasName("pk_fame_entries");

                    b.HasIndex("GuildId", "InductedAt")
                        .HasDatabaseName("ix_fame_entries_guild_id_inducted_at");

                    b.ToTable("fame_entries", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Fame.FameReaction", b =>
                {
                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<decimal>("ReactorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("reactor_id");

                    b.Property<string>("Emoji")
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("MessageId", "ReactorId", "Emoji")
                        .HasName("pk_fame_reactions");

                    b.ToTable("fame_reactions", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.GameServers.GameServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_game_servers");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_game_servers_guild_id");

                    b.ToTable("game_servers", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.GameServers.ServerSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal?>("BoardChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("board_channel_id");

                    b.Property<int>("FailuresBeforeOffline")
                        .HasColumnType("integer")
                        .HasColumnName("failures_before_offline");

                    b.Property<int>("MaxPerMember")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_member");

                    b.Property<int>("MaxServers")
                        .HasColumnType("integer")
                        .HasColumnName("max_servers");

                    b.Property<bool>("MembersCanAdd")
                        .HasColumnType("boolean")
                        .HasColumnName("members_can_add");

                    b.Property<int>("PollSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_seconds");

                    b.HasKey("GuildId")
                        .HasName("pk_server_settings");

                    b.ToTable("server_settings", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.Bets.Bet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<bool>("ClosedShown")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_shown");

                    b.Property<DateTimeOffset>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CreatorCanBet")
                        .HasColumnType("boolean")
                        .HasColumnName("creator_can_bet");

                    b.Property<double>("CreatorCutPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("creator_cut_percent");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<double>("HouseCutPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("house_cut_percent");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<decimal?>("ResolvedById")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("resolved_by_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int?>("WinningOption")
                        .HasColumnType("integer")
                        .HasColumnName("winning_option");

                    b.HasKey("Id")
                        .HasName("pk_bets");

                    b.HasIndex("GuildId", "State")
                        .HasDatabaseName("ix_bets_guild_id_state");

                    b.ToTable("bets", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.Bets.BetPayout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<long>("BetId")
                        .HasColumnType("bigint")
                        .HasColumnName("bet_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<bool>("Reversed")
                        .HasColumnType("boolean")
                        .HasColumnName("reversed");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bet_payouts");

                    b.HasIndex("BetId")
                        .HasDatabaseName("ix_bet_payouts_bet_id");

                    b.ToTable("bet_payouts", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.Bets.BetStake", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<long>("BetId")
                        .HasColumnType("bigint")
                        .HasColumnName("bet_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Option")
                        .HasColumnType("integer")
                        .HasColumnName("option");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bet_stakes");

                    b.HasIndex("BetId", "UserId")
                        .HasDatabaseName("ix_bet_stakes_bet_id_user_id");

                    b.ToTable("bet_stakes", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.MischiefEffect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EndedById")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("ended_by_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<double>("Paid")
                        .HasColumnType("double precision")
                        .HasColumnName("paid");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_mischief_effects");

                    b.HasIndex("GuildId", "TargetId", "Kind", "EndsAt")
                        .HasDatabaseName("ix_mischief_effects_guild_id_target_id_kind_ends_at");

                    b.ToTable("mischief_effects", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Mischief.Rename", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("NewName")
                        .HasColumnType("text")
                        .HasColumnName("new_name");

                    b.Property<string>("OldName")
                        .HasColumnType("text")
                        .HasColumnName("old_name");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_renames");

                    b.HasIndex("GuildId", "TargetId", "CreatedAt")
                        .HasDatabaseName("ix_renames_guild_id_target_id_created_at");

                    b.ToTable("renames", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Modules.ModuleSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Module")
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.HasKey("GuildId", "Module")
                        .HasName("pk_module_settings");

                    b.ToTable("module_settings", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Notifications.NotificationPreference", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("GuildId", "UserId", "Topic")
                        .HasName("pk_notification_preferences");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Points.PointAccount", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision")
                        .HasColumnName("balance");

                    b.Property<double>("Chat")
                        .HasColumnType("double precision")
                        .HasColumnName("chat");

                    b.Property<double>("Given")
                        .HasColumnType("double precision")
                        .HasColumnName("given");

                    b.Property<DateTimeOffset?>("LastChatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_chat_at");

                    b.Property<double>("PendingEarned")
                        .HasColumnType("double precision")
                        .HasColumnName("pending_earned");

                    b.Property<double>("PendingExpired")
                        .HasColumnType("double precision")
                        .HasColumnName("pending_expired");

                    b.Property<DateTimeOffset?>("PendingSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_since");

                    b.Property<double>("Received")
                        .HasColumnType("double precision")
                        .HasColumnName("received");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("Voice")
                        .HasColumnType("double precision")
                        .HasColumnName("voice");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_point_accounts");

                    b.ToTable("point_accounts", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Points.PointEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_point_entries");

                    b.HasIndex("GuildId", "UserId", "CreatedAt")
                        .HasDatabaseName("ix_point_entries_guild_id_user_id_created_at");

                    b.ToTable("point_entries", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Quotes.Quote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AddedById")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("added_by_id");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("SaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("said_at");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_quotes_guild_id");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Quotes.QuoteLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("QuoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("quote_id");

                    b.Property<decimal?>("SpeakerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("speaker_id");

                    b.Property<string>("SpeakerName")
                        .HasColumnType("text")
                        .HasColumnName("speaker_name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_quote_lines");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_quote_lines_quote_id");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_quote_lines_speaker_id");

                    b.ToTable("quote_lines", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.DynamicVoiceChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("owner_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_dynamic_voice_channels");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_dynamic_voice_channels_guild_id");

                    b.ToTable("dynamic_voice_channels", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.VoiceHub", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_voice_hubs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_voice_hubs_guild_id");

                    b.ToTable("voice_hubs", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Quotes.QuoteLine", b =>
                {
                    b.HasOne("THOBOTTO.Quotes.Quote", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_lines_quotes_quote_id");
                });

            modelBuilder.Entity("THOBOTTO.Quotes.Quote", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
