// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THOBOTTO.Data;

#nullable disable

namespace THOBOTTO.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20261007210114_DynamicVoice")]
    partial class DynamicVoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THOBOTTO.Data.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("GuildId", "CreatedAt")
                        .HasDatabaseName("ix_audit_entries_guild_id_created_at");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Data.EnabledModule", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Module")
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("GuildId", "Module")
                        .HasName("pk_enabled_modules");

                    b.ToTable("enabled_modules", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.DynamicVoiceChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("owner_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_dynamic_voice_channels");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_dynamic_voice_channels_guild_id");

                    b.ToTable("dynamic_voice_channels", (string)null);
                });

            modelBuilder.Entity("THOBOTTO.Voice.VoiceHub", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_voice_hubs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_voice_hubs_guild_id");

                    b.ToTable("voice_hubs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
